#include "tile_object.h"

const unsigned int tiles_object_indexes[] =
{
	TILE_WAVES_BLOCK,
	TILE_BRIDGE_MIDD,
	TILE_BRIDGE_SIDE,
	TILE_BRIDGE_SIGN,
	TILE_ISLAND_MIDD,
	TILE_ISLAND_LEFT,
	TILE_ISLAND_RGHT,
	TILE_ISLAND_SIGN,
	TILE_ISLAND_TREEL,
	TILE_ISLAND_TREER,
	TILE_TURTLE_SEA1,
	TILE_TURTLE_SEA2,
	TILE_TURTLE_FLY1,
	TILE_TURTLE_FLY2,
	TILE_TURTLE_FLY3,
	TILE_TURTLE_FLY4,

	TILE_BRIDGE_SIDE,
	TILE_ISLAND_GOAL,
	TILE_BRIDGE_GOAL,
};

const unsigned char tiles_object_platform[] =
{
	00, 16, 16, 16, 18, 18, 18, 18,
	18, 18, 19, 18,	17, 16, 15, 14,
};
